Add solution. Manual tests similar to example, but failing 1 npm sort by length test
mate-academy/react_list-of-goods-hooks pull request #1024
Opened 2023-06-15 22:17 UTC by PanyaPrimal

[DEMO LINK](https://PanyaPrimal.github.io/react_list-of-goods-hooks/)

2023-06-16 07:02 UTC, 33Orange requested changes
Almost done

A few moments to fix

2023-06-19 06:58 UTC, 33Orange requested changes
Almost done

2023-06-19 06:58 UTC, 33Orange commented on src/App.tsx
> +  };
Why did this function still remain in `App` component ?
Remove it from app component

2023-06-19 06:58 UTC, 33Orange commented on src/App.tsx
> +    setIsReversed(false);
Why `sortAlphabetically` changing `isReversed` ?
Buttons should have 1 action

2023-06-19 06:58 UTC, 33Orange commented on src/App.tsx
> +  };
Same here

2023-06-28 11:49 UTC, dffUqp approved these changes

2025-12-18 12:06 UTC, closed without merging