added solution
mate-academy/react_list-of-goods-hooks pull request #1052
Opened 2023-06-27 15:27 UTC by sheva10barca

[DEMO LINK](https://sheva10barca.github.io/react_list-of-goods-hooks/)

2023-06-27 16:24 UTC, Viktor-Kost requested changes
GJ!
Some types fixes needed

2023-06-27 16:24 UTC, Viktor-Kost commented on src/App.tsx
> +  const sortByAlphabet = () => {
Add a return type for the `sortByAlphabet` function. Example: `const sortByAlphabet = (): void => {...}`

2023-06-27 16:24 UTC, Viktor-Kost commented on src/App.tsx
> +export function getReorderedGoods(
It's a good practice when you add return type for functions
Example: `function getReorderedGoods(...): string[] {...}`

2023-06-27 16:24 UTC, Viktor-Kost commented on src/App.tsx
> +  const reverseGoodsList = () => {
Add a return type for the `reverseGoodsList` function. Example: `const reverseGoodsList = (): void => {...}`

2023-06-27 16:24 UTC, Viktor-Kost commented on src/App.tsx
> +  const resetHandler = () => {
Add a return type for the `resetHandler` function. Example: `const resetHandler = (): void => {...}`

2023-06-27 16:24 UTC, Viktor-Kost commented on src/App.tsx
> +  const sortByLength = () => {
Add a return type for the `sortByLength` function. Example: `const sortByLength = (): void => {...}`

2023-06-28 07:07 UTC, etojeDenys approved these changes
lgtm

2025-02-09 19:05 UTC, closed without merging