implement typescript into static list of todos
mate-academy/react_list-of-goods-hooks pull request #1265
Opened 2023-09-05 15:47 UTC by rostyslav48

[DEMO LINK](https://rostyslav48.github.io/react_list-of-goods-hooks/)

2023-09-05 19:03 UTC, Vannnkof approved these changes
Good job!

2023-09-06 08:22 UTC, Moroz-Dmytro requested changes

2023-09-06 08:22 UTC, Moroz-Dmytro commented on src/App.tsx
> +import cn from 'classnames';
For the future, better not to use such short names, you can name it `classnames` here

2023-09-06 08:22 UTC, Moroz-Dmytro commented on src/App.tsx
> +enum SortField {
```suggestion
enum SortType {
```

2023-09-06 08:22 UTC, Moroz-Dmytro commented on src/App.tsx
> +enum SortField {
<img width="748" alt="image" src="https://github.com/mate-academy/react_list-of-goods-hooks/assets/86789161/03682096-f63a-4fbd-a4cb-6daae14f308f">

2023-09-06 08:22 UTC, Moroz-Dmytro commented on src/App.tsx
> +  const [sortField, setSortField] = useState<SortField>(SortField.Default);
```suggestion
  const [sortType, setSortType] = useState<SortType>(SortType.Default);
```

2023-09-06 08:22 UTC, Moroz-Dmytro commented on src/App.tsx
> +  const isChanged = () => Boolean(sortField) || isReversed;
```suggestion
  const isResetButtonVisible = Boolean(sortField) || isReversed;
```

2023-09-06 08:22 UTC, Moroz-Dmytro commented on src/App.tsx
> +  const resetFilterOptions = (): void => {
```suggestion
  const handleResetButtonClick = (): void => {
```

2023-09-06 08:22 UTC, Moroz-Dmytro commented on src/App.tsx
> +          })}
```suggestion
          className={cn(
            'button',
            'is-info',
            {'is-light': SortField.Alphabet !== sortField}
          )}
```

2023-09-06 08:22 UTC, Moroz-Dmytro commented on src/App.tsx
> +          })}
Same in other places

2023-09-06 08:22 UTC, Moroz-Dmytro commented on src/App.tsx
> +          onClick={() => setIsReversed(!isReversed)}
```suggestion
          onClick={() => setIsReversed(isReversed => !isReversed)}
```

2023-09-06 08:22 UTC, Moroz-Dmytro commented on src/App.tsx
> +        {isChanged() && (
```suggestion
        {isResetButtonVisible && (
```

2023-09-06 08:22 UTC, Moroz-Dmytro commented on src/App.tsx
> +        {isChanged() && (
It should be constant value, not function

2023-09-07 07:05 UTC, Moroz-Dmytro approved these changes
GJ 👍 
But check comments below

2023-09-07 07:05 UTC, Moroz-Dmytro commented on src/App.tsx
> +          onClick={() => setIsReversed(() => !isReversed)}
```suggestion
          onClick={() => setIsReversed(prevIsReversed => !prevIsReversed)}
```

You need to take previous value

2023-09-07 07:05 UTC, Moroz-Dmytro commented on src/App.tsx
> +          <li data-cy="Good" key={id}>{product}</li>
```suggestion
          <li data-cy="Good" key={id}>
            {product}
          </li>
```

2025-08-31 20:07 UTC, closed without merging