done
mate-academy/react_list-of-goods-hooks pull request #1735
Opened 2024-03-21 10:08 UTC by TideTwo

[DEMO LINK](https://tidetwo.github.io/react_list-of-goods-hooks/)

2024-03-22 11:43 UTC, asakevych requested changes
good job! :rocket: :fire: just small changes are needed

2024-03-22 11:43 UTC, asakevych commented on src/App.tsx
> +  console.log(sortType, isReversed);
remove console logs

2024-03-22 11:43 UTC, asakevych commented on src/App.tsx
> +  const [sortType, setSortType] = React.useState(SortType.NONE);
add types

2024-03-25 11:11 UTC, choeqq approved these changes

2025-01-04 13:06 UTC, closed without merging