solution
mate-academy/react_list-of-goods-hooks pull request #204
Opened 2022-07-14 14:41 UTC by Pavlo000

[DEMO LINK](https://Pavlo000.github.io/react_list-of-goods/)

2022-07-14 15:26 UTC, liliia-livandovskaya approved these changes
GJ!

2022-07-15 08:43 UTC, mykola-koval requested changes

2022-07-15 08:43 UTC, mykola-koval commented on src/App.tsx
> +    sortBy: '',
use separate hooks for each of the variables

2022-07-15 13:13 UTC, mykola-koval approved these changes

2022-07-15 13:13 UTC, mykola-koval commented on src/App.tsx
> +        return 0;
i'd use a single function for this logic and removed usage of useState `setSortBy`

2024-11-26 18:26 UTC, closed without merging