solution
mate-academy/react_list-of-goods-hooks pull request #22
Opened 2022-02-21 13:23 UTC by maksym-mishchanchuk

[DEMO LINK](https://maksym-mishchanchuk.github.io/react_list-of-goods/)

2022-02-21 16:22 UTC, jursylian approved these changes
Well done!

2022-02-22 08:57 UTC, OleksiiBlezniuk requested changes
Кнопки работают некорректно, исправь пожалуйста

https://user-images.githubusercontent.com/84275496/155097484-c99a0e3e-1fa2-4295-b7be-691c628f0cc7.mov

2022-02-22 08:57 UTC, OleksiiBlezniuk commented on src/App.tsx
> +  const [isVisibleGoods, setIsVisibleGoods] = useState(false);
```suggestion
  const [isGoodsVisible, setIsGoodsVisible] = useState(false);
```

2022-02-22 15:29 UTC, OleksiiBlezniuk approved these changes

2023-09-04 18:45 UTC, closed without merging