Develop
mate-academy/react_list-of-goods-hooks pull request #268
Opened 2022-08-09 13:28 UTC by Kras4iy

[DEMO LINK](https://Kras4iy.github.io/react_list-of-goods/)

2022-08-09 13:54 UTC, oleksandr-kotliarov approved these changes
good

2022-08-09 15:46 UTC, LordAsmodey approved these changes
Looks good
but styles...)))

2022-08-10 07:31 UTC, ivan-kadykalo requested changes
Add styles and let's show the active sort button when it clicked and applied.

2022-08-10 12:18 UTC, Ihor-Karpyn approved these changes

2022-08-10 12:18 UTC, Ihor-Karpyn commented on src/App.tsx
> +  const [sortType, setSortType] = useState(0);
why it's number, let's add enum

2022-08-10 12:18 UTC, Ihor-Karpyn commented on src/App.tsx
> +  const [reverse, setReverse] = useState(false);
all boolean vars should start with `is`

2026-04-28 18:12 UTC, closed without merging