Solution for `React Goods List with Hooks`
mate-academy/react_list-of-goods-hooks pull request #51
Opened 2022-03-31 15:48 UTC by jstmpelowycz

**[DEMO LINK](https://jstmpelowycz.github.io/react_list-of-goods-hooks/)**

2022-04-01 09:52 UTC, solaryasha requested changes

2022-04-01 09:52 UTC, solaryasha commented on src/App.tsx
> +  };
Використай useCallback, якщо прокидуєш колбек в інший компонент

2022-04-01 09:52 UTC, solaryasha commented on src/components/GoodsList/GoodsList.tsx
> +  const [maxLength] = useState(10);
No, це зайве

2022-04-01 09:52 UTC, solaryasha commented on src/components/GoodsList/GoodsList.tsx
> +  const [maxLength] = useState(10);
Ці константи можна створити поза компонентом

2022-04-01 09:52 UTC, solaryasha commented on src/components/Selector/Selector.tsx
> +export const Selector: FC<Props> = ({
Використай react.memo

2022-04-01 09:52 UTC, solaryasha commented on src/components/Selector/Selector.tsx
> +  onChangeFunc: (value: string) => void;
```suggestion
  onChange: (value: string) => void;
```

2022-04-01 09:52 UTC, solaryasha commented on src/components/GoodsList/GoodsList.tsx
> +  const handleResetClick = () => {
Якщо колбеки передаєш в інші компоненти, то використай useCallback

2022-04-04 10:01 UTC, Ihor-Karpyn approved these changes

2024-01-08 17:07 UTC, closed without merging